### PR TITLE
proc tree view: if there's more than 40 width left, print full cmd

### PR DESCRIPTION
**Pull request by Superty**

### CODE REVIEW

**Comment by aristocratos** [comment]
https://github.com/aristocratos/btop/blob/main/CONTRIBUTING.md

**Comment by Superty** [comment]
PR for #453

**Review by aristocratos — APPROVED** [review]
Looks good!
Thanks for contributing :)

**Comment by stefanos82** [comment]
It does not produce a clean output on my monitor; it looks rather broken, just take a look at the left side of expanded process tree and the width of parentheses on the far right side.

image

**Comment by stefanos82** [comment]
Another issue I have noticed is in the footer area; where is `select`, `info`, and the whole word for `terminate`?

image

**Comment by Superty** [comment]
Thanks for reporting, should be fixed by #454.

**Comment by stefanos82** [comment]
My maximum resolution is `1360x768` if it helps; it's presumably an HDTV monitor.

**Pull request merged**
