### PR TITLE
Add option for filtering kernel processes.

### PR DESCRIPTION
**Pull request by 0xJoeMama**
It's not ready, however I think it's worth creating a PR for.

### CODE REVIEW

**Comment by 0xJoeMama** [comment]
Also I still need to fix the formatting changes.

**Comment by aristocratos** [comment]
@0xJoeMama 
You should remove the `.clang-format` file and submit as a separate PR with a good explanation why it should be considered, as per https://github.com/aristocratos/btop/blob/main/CONTRIBUTING.md

`.gitignore` should also be reverted, if you have files you want to ignore in your local copy use `.git/info/exclude` file which is private.

As for the other files, all formatting need to be reset. Easiest might be to start clean from `main` and copy paste your changes.

**Review by aristocratos — CHANGES_REQUESTED** [review]
Needed changes in comment above.

**Comment by 0xJoeMama** [comment]
I will close this and promptly open one with the branch with the correct fixes.

**Pull request closed without merging**
