### PR TITLE
conditional compile on Big Sur and up

### PR DESCRIPTION
**Pull request by joske**
Conditional compile the IOKit stuff only on macOS Big Sur and above.

### CODE REVIEW

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
Can we use `101504` instead of `__MAC_10_15_4`? The definition of this string is missing in older versions of the macOS SDK.

**Comment by joske** [comment]
Yes, that makes sense!

**Review by aristocratos — APPROVED** [review]
Nice work!

**Comment by aristocratos** [comment]
Should this be merged or is there more changes coming and this should be kept open?

**Comment by joske** [comment]
I think this can go in as is. I don't have anything else for the moment.

**Pull request merged**
