### PR TITLE
Fix coretemp iteration due to missing temp9_input (i9-9940X)

### PR DESCRIPTION
**Pull request by KFilipek**
Hi all,
This PR introduces small change I made accidentally - I've downloaded snap package with older version of btop and shows temperatures always 0'C. I didn't compile master branch before I've started fixing, don't ask.
#### Story behind changes
Anyway, after some reconnaissance I realized that I can only set temperature sensor for first few cores and package.
I have Intel i9-9940X (14 cores, 28 threads), so I should have `temp(1-15)_input`, but...
```sh
$ ls /sys/devices/platform/coretemp.0/hwmon/hwmon*/temp*_input
/sys/devices/platform/coretemp.0/hwmon/hwmon1/temp10_input
/sys/devices/platform/coretemp.0/hwmon/hwmon1/temp11_input
/sys/devices/platform/coretemp.0/hwmon/hwmon1/temp12_input
/sys/devices/platform/coretemp.0/hwmon/hwmon1/temp13_input
/sys/devices/platform/coretemp.0/hwmon/hwmon1/temp14_input
/sys/devices/platform/coretemp.0/hwmon/hwmon1/temp15_input
/sys/devices/platform/coretemp.0/hwmon/hwmon1/temp16_input
/sys/devices/platform/coretemp.0/hwmon/hwmon1/temp1_input
/sys/devices/platform/coretemp.0/hwmon/hwmon1/temp2_input
/sys/devices/platform/coretemp.0/hwmon/hwmon1/temp3_input
/sys/devices/platform/coretemp.0/hwmon/hwmon1/temp4_input
/sys/devices/platform/coretemp.0/hwmon/hwmon1/temp5_input
/sys/devices/platform/coretemp.0/hwmon/hwmon1/temp6_input
/sys/devices/platform/coretemp.0/hwmon/hwmon1/temp7_input
/sys/devices/platform/coretemp.0/hwmon/hwmon1/temp8_input
```
Surprise, CPU topology, I have `temp(1-8 and 10-16)_input`.
It's matches:
```sh
$ cat /sys/devices/system/cpu/cpu7/topology/core_id
8
$ cat /sys/devices/system/cpu/cpu6/topology/core_id
6
```

#### Proposed solution:
Iteration through files matching `tempX_input` pattern, it should cover my case and also bug: #151 

#### Commit description:
There are cases when some files are missing:
1. Due to specific CPU topology (e.g. {cpu6: core_id=6; but cpu7: core_id=8})
2. On architectures older than SandyBridge (missing per-package sensor)

P.S.
Great app, I love it.

### CODE REVIEW

**Comment by KFilipek** [comment]
According to structure I got on Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz:
```
/sys/class/hwmon/hwmon0/temp1_input
/sys/class/hwmon/hwmon1/temp1_crit
/sys/class/hwmon/hwmon1/temp1_crit_alarm
/sys/class/hwmon/hwmon1/temp1_input
/sys/class/hwmon/hwmon1/temp1_label
/sys/class/hwmon/hwmon1/temp1_max
/sys/class/hwmon/hwmon1/temp2_crit
/sys/class/hwmon/hwmon1/temp2_crit_alarm
/sys/class/hwmon/hwmon1/temp2_input
/sys/class/hwmon/hwmon1/temp2_label
/sys/class/hwmon/hwmon1/temp2_max
/sys/class/hwmon/hwmon1/temp3_crit
/sys/class/hwmon/hwmon1/temp3_crit_alarm
/sys/class/hwmon/hwmon1/temp3_input
/sys/class/hwmon/hwmon1/temp3_label
/sys/class/hwmon/hwmon1/temp3_max
/sys/class/hwmon/hwmon1/temp4_crit
/sys/class/hwmon/hwmon1/temp4_crit_alarm
/sys/class/hwmon/hwmon1/temp4_input
/sys/class/hwmon/hwmon1/temp4_label
/sys/class/hwmon/hwmon1/temp4_max
/sys/class/hwmon/hwmon1/temp5_crit
/sys/class/hwmon/hwmon1/temp5_crit_alarm
/sys/class/hwmon/hwmon1/temp5_input
/sys/class/hwmon/hwmon1/temp5_label
/sys/class/hwmon/hwmon1/temp5_max
```
I changed the following:
1. Find a file that starts with "temp" and ends with "_label" to mitigate case like above (only `/sys/class/hwmon/hwmon0/temp1_input` without any other files like `*_crit`, `*_label` etc).
2. Missing files like `temp1_label` (PR #151) or `temp9_label` on i9-9940X are not problem.

I can test on 2 socket machine also to see CPU topology.

Best regards,
Krzysztof Filipek

**Review by aristocratos — COMMENTED** [review]
Looks good, great work!
If you're done with it I will merge in next release.

**Review by aristocratos — APPROVED** [review]

**Comment by ChUnterberger** [comment]
I think this PR needs another round. While it finds all the sensors on all the machines i tested, i noticed a new bug inroduced with this PR which messes up the core mapping.

You can reproduce the issue by stressing a single core and checking the core temperature.
You can see that on some machines this will not match with the core which has the 100% load.
I tested this with the stress tool.

`stress -c 1` for single core load.

The reason for this is that the `fs::directory_iterator` at [https://github.com/KFilipek/btop/blob/fix-iterate_through_coretemp/src/linux/btop_collect.cpp#L280](https://github.com/KFilipek/btop/blob/fix-iterate_through_coretemp/src/linux/btop_collect.cpp#L280) does not return the results sorted and `core_sensors` is expected sorted because at [https://github.com/KFilipek/btop/blob/fix-iterate_through_coretemp/src/linux/btop_collect.cpp#L372](https://github.com/KFilipek/btop/blob/fix-iterate_through_coretemp/src/linux/btop_collect.cpp#L372) the index of the core is used as a index to the vector position.
```
core_sensors
[0] "coretemp/Core 1"
[1] "coretemp/Core 2"
[2] "coretemp/Core 3"
[3] "coretemp/Core 0"
```
For this reason the code will show all core temperatures offset by 1.

I think we either need to sort before we insert or we need to replace the vector with a map and use the core id as index.

BTW:  [https://github.com/KFilipek/btop/blob/fix-iterate_through_coretemp/src/linux/btop_collect.cpp#L312](https://github.com/KFilipek/btop/blob/fix-iterate_through_coretemp/src/linux/btop_collect.cpp#L312) still uses the old style for loop. I think for consistency we would want the same style.

**Comment by aristocratos** [comment]
@ChUnterberger @KFilipek 
> I think we either need to sort before we insert or we need to replace the vector with a map and use the core id as index.

Since the function is only run once the easiest way to fix this would probably be to just add:
```c++
else rng::sort(core_sensors, rng::less{});
```
after line 336.

**Comment by ChUnterberger** [comment]
@aristocratos This fixes the issue for me but would not work on machines with more than 10 cores.
This is because the sort would order the cores

core_sensors
[0] "coretemp/Core 0"
[1] "coretemp/Core 1"
[2] "coretemp/Core 10"
[3] "coretemp/Core 2"
```

**Comment by aristocratos** [comment]
@ChUnterberger @KFilipek 
Oops :)

Should be fixed by:
```c++
else {
	rng::sort(core_sensors, rng::less{});
	rng::stable_sort(core_sensors, [](const auto& a, const auto& b){
		return a.size() < b.size();
	});
}
```

**Comment by aristocratos** [comment]
Yeah, should work:
https://godbolt.org/z/necEnv945

As long as the assumption that the prefix before the number is the same length holds true, this will work.

**Comment by ChUnterberger** [comment]
Yes either this or this should do the trick.

```c
else rng::sort(core_sensors, [](const auto a, const auto b) { 
   return std::stoi(a.substr(a.find_first_of("0123456789"))) < std::stoi(b.substr(b.find_first_of("0123456789")));
});
```

**Comment by aristocratos** [comment]
@ChUnterberger 
Yeah, that's neat, didn't realize `string::find_first_of()` would match _any_ of the characters specified.

**Comment by aristocratos** [comment]
@ChUnterberger
However the `stoi` opens up for a `std::out_of_range` exception if for some reason the name doesn't include a number, so would be slightly less safe.

**Comment by ChUnterberger** [comment]
@aristocratos 
True, the code makes some assumptions about the format of the strings which if violated causes a runtime exception. 

The first code would fail to sort correctly if numbers are padded with 0. E.g. `coretemp/Core 009` while the second code could cause a runtime exception if the passed string does not contain a number, is in hex or oct or if the value is out of range.

Both are not likely to occur but to be on the safe side a implementation which cannot throw unhandled runtime errors is preferred even if it silently hides a potential core mapping issue.

**Comment by aristocratos** [comment]
Merged in v1.1.2

@KFilipek thanks for contributing!
@ChUnterberger thanks for the input!

**Pull request merged**
