### PR TITLE
OSX: use the first IP of the interface

### PR DESCRIPTION
**Pull request by correabuscar**
... instead of the last.

Side effect of this is that it also detects when the current IP gets removed from the interface, instead of keep displaying the old IP.

This is PR #457 but for OSX, not Linux.

### CODE REVIEW

**Comment by correabuscar** [comment]
What the? :))
```
Building btop++ (v1.2.12) macos x86_64
Compiling src/btop.cpp
Compiling src/btop_config.cpp
Compiling src/btop_draw.cpp
8%-> obj/btop_config.o (1.6MiB) ()
Compiling src/btop_input.cpp
16%-> obj/btop.o (2.1MiB) ()
Compiling src/btop_menu.cpp
24%-> obj/btop_input.o (1.6MiB) ()
Compiling src/btop_shared.cpp
32%-> obj/btop_draw.o (2.8MiB) ()
Compiling src/btop_theme.cpp
40%-> obj/btop_menu.o (2.3MiB) ()
Compiling src/btop_tools.cpp
49%-> obj/btop_shared.o (2.1MiB) ()
Compiling src/osx/btop_collect.cpp
57%-> obj/btop_theme.o (1.6MiB) ()
Compiling src/osx/sensors.cpp
65%-> obj/osx/sensors.o ( 60KiB) ()
Compiling src/osx/smc.cpp
81%-> obj/osx/smc.o ( 28KiB) ()
81%-> obj/btop_tools.o (1.6MiB) ()
90%-> obj/osx/btop_collect.o (2.7MiB) ()

Linking and optimizing binary...
ld: warning: option -s is obsolete and being ignored
0  0x10568cffa  __assert_rtn + 139
1  0x1054c028d  mach_o::relocatable::Parser<x86_64>::parse(mach_o::relocatable::ParserOptions const&) + 4989
2  0x1054b0f8f  mach_o::relocatable::Parser<x86_64>::parse(unsigned char const*, unsigned long long, char const*, long, ld::File::Ordinal, mach_o::relocatable::ParserOptions const&) + 207
3  0x1054fe404  archive::File<x86_64>::makeObjectFileForMember(archive::File<x86_64>::Entry const*) const + 1268
4  0x1054fda8b  archive::File<x86_64>::File(unsigned char const*, unsigned long long, char const*, long, ld::File::Ordinal, archive::ParserOptions const&) + 1035
5  0x1054fcc72  archive::parse(unsigned char const*, unsigned long long, char const*, long, ld::File::Ordinal, archive::ParserOptions const&) + 146
6  0x105527c8e  ld::tool::InputFiles::makeFile(Options::FileInfo const&, bool) + 2734
7  0x10552afa0  ___ZN2ld4tool10InputFilesC2ER7Options_block_invoke + 48
8  0x7ff80bbce34a  _dispatch_client_callout2 + 8
9  0x7ff80bbdf8f5  _dispatch_apply_invoke + 213
10  0x7ff80bbce317  _dispatch_client_callout + 8
11  0x7ff80bbddc0c  _dispatch_root_queue_drain + 673
12  0x7ff80bbde25c  _dispatch_worker_thread2 + 160
13  0x7ff80bd81f8a  _pthread_wqthread + 256
A linker snapshot was created at:
	/tmp/btop-2022-11-06-074248.ld-snapshot
ld: Assertion failed: (_file->_atomsArrayCount == computedAtomCount && "more atoms allocated than expected"), function parse, file macho_relocatable_file.cpp, line 2061.
collect2: error: ld returned 1 exit status
make: *** [btop] Error 1
Error: Process completed with exit code 2.
```

**Comment by correabuscar** [comment]
> The issue is with XCode 14.0 version, which I have tested and confirmed.
> Downgrade your command line tools version to 13.4 and it will be resolved.

> there is another way to solve this problem
> `#pragma GCC optimize("O2")`
> and wait untill Xcode solve this problem

both from: https://stackoverflow.com/q/73714336/19999437

**Comment by aristocratos** [comment]
@correabuscar 
Yeah noticed it when compiling on macos13: https://github.com/aristocratos/btop/issues/451
Seems like githubs macos12 have upgraded the xcode tools to the bugged version.

It's fixed in the workflow now with manual selection of xcode, but it reuses the old workflow file when I try to re-run the job for this pull request.

Do you mind pushing another commit (with just a comment or something) so that the workflow runs again with updated files.

**Comment by correabuscar** [comment]
> Do you mind pushing another commit (with just a comment or something) so that the workflow runs again with updated files.

I force pushed the amended commit by changing a space in commit msg from `... instead of the last.` to `...instead of the last.` It has different commit hash...

**Review by aristocratos — APPROVED** [review]

**Pull request merged**
