### PR TITLE
Add CMake support for Linux

### PR DESCRIPTION
**Pull request by nobounce**
Some parts for the other OSes are already there but I'm still testing.

Don't know if the documentation is to your liking, feedback appreciated!

Closes: #583

### CODE REVIEW

**Review by aristocratos — CHANGES_REQUESTED** [review]
@nobounce 
Looks good so far, is it ready to merge?

I would like to ask that you move the instructions for the regular Makefile above the CMake instructions and add `(Community maintained)` or something similar after `### With CMake` if that's alright?

**Comment by nobounce** [comment]
Yes, I've addressed the review

Also see the commit message for some quirks!

Otherwise ready to go

**Comment by aristocratos** [comment]
Unless you plan to update the CMakeLists.txt file for every release, look at the file @jan-guenter made: https://github.com/jan-guenter/btop/blob/main/CMakeLists.txt for how to get the version string from the source.

> FreeBSD is not able to create a static executable for now.

This is already known for both FreeBSD and MacOS, which is why the Makefile only statically links libgcc and libstdc++ for them. Something that's also mentioned in the compilation instructions in the README.md

**Comment by nobounce** [comment]
> > FreeBSD is not able to create a static executable for now.

This was just referring this particular `CMakeLists.txt` on FreeBSD, I've not added the work around :)

Regarding the version:
I'd rather see the build system like Make or CMake define a version and pass it to the source. This allows for things like the git hash to be appended to the version if desired.
Otherwise I can update this manually or even with CI on my branch

**Comment by nobounce** [comment]
Ok, I'm a lot happier now :)
Added some useful options and documented them.

Added the `cmake/Modules` directory which contains files to dynamically detect the libraries required on FreeBSD.

Static linking in FreeBSD works now with Clang, however Clang only works with FreeBSD 14 :/
 (or with GCC's libraries which defeats the point kind of). The install `libc++` version depends on the FreeBSD release and cant be updated with a port

**Review by aristocratos — APPROVED** [review]

**Comment by aristocratos** [comment]
@nobounce 
You should be able to merge this yourself since it's approved or am I wrong in that assumption?

If the PR is done that is?

**Comment by nobounce** [comment]
@aristocratos 
for me it says:
>  Changes approved
1 approving review by reviewers with write access.
This branch has no conflicts with the base branch
Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.

**Pull request merged**
