### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by pallebone**

### CODE REVIEW

**Comment by pallebone** [comment]
The final theme file should have this change:
# Mem/Disk available meter
theme[available_start]="#ff0000"
theme[available_mid]="#ccff66"
theme[available_end]="#00ff00"

Hopefully that commit came through I uploaded a theme file without that change the first time and tried to change it afterwards.

P

**Comment by pallebone** [comment]
Let me know if there are any problems/issues or anything you want me to do :)

**Comment by aristocratos** [comment]
@pallebone 
Well you'll need to remove the extra .theme file in the top folder.
Please provide a screenshot also.

**Comment by pallebone** [comment]
Sorry! As you can tell I am very new so thank you for the hand holding. Apologies again for the error. I believe I have fixed it now I hope. Unsure if relevant but I use the snap version of btop.

I have deleted that file. 

Here is a ss:
Screenshot from 2022-02-27 12-53-29

**Comment by pallebone** [comment]
The mem cached and free should be orange at the bottom bar and bars stacked above should be green in the correct version.
Thats why I was checking this was correct:
theme[available_start]="#ff0000"
theme[available_mid]="#ccff66"
theme[available_end]="#00ff00"

Kind regards
Pete

**Comment by pallebone** [comment]
Here is another SS with some memory load:
Screenshot from 2022-02-27 12-59-18

**Comment by pallebone** [comment]
@aristocratos was that ok?

**Review by aristocratos — APPROVED** [review]
@pallebone 
It's a little too much purple for my particular taste, but I'm sure there's others who will enjoy it :)

Will be included in next release.
Thanks for contributing!

**Comment by pallebone** [comment]
Cool thank you.

**Pull request merged**
